### ISSUE TITLE
Nomina

### ISSUE THREAD

**Issue by antonioalvarezm** [GrupoCorasa/factura-electronica#1]
Tienen algun ejemplo de como extraer los datos de Nomina 1.2 del cfdi 3.3?

**Comment by hortegag91** [comment]
Para extraer la información de la nómina tendrías que leer el XML correspondiente como lo marca el readme, despues tienes que llamar al método getComplementos y verificar si el object es una instancia de objeto v12.Nomina.
Si requieres más apoyo avisame.

**Comment by antonioalvarezm** [comment]
Me parece que seria la unica manera de extraer los datos de nomina recorriendo cada nodo y atributo de cada elemento

List<Complemento> complementos = comprobante.getComplemento();
for (i = 0; i < complementos.size(); i++) {
	List<Object> list = complementos.get(i).getAny();
	for (j = 0; j < list.size(); j++) {
		if (list.get(j).toString().toLowerCase().contains("nomina")) {
			Element el = (Element) list.get(j);
		}
	}
}

A diferencia de TimbreFiscal este objeto si es reconocido 
List<Complemento> complementos = comprobante.getComplemento();
	for (i = 0; i < complementos.size(); i++) {
	List<Object> list = complementos.get(i).getAny();
	for (j = 0; j < list.size(); j++) {
		if (list.get(j).toString().toLowerCase().contains("timbrefiscaldigital")) {
			tfd = (TimbreFiscalDigital) list.get(j);
			break;
		}
	}
}

Lo que noto es que TimbreFiscal si es un nodo y nomina es un arreglo

**Comment by hortegag91** [comment]
Olvidé comentarte que en base al documento que leas, debes especificar la variable contexts.
Te anexo un ejemplo que acabo de probar en un main:
`CFDv33 cfd = new CFDv33(new FileInputStream(file), "mx.bigdata.sat.common.nomina.v12.schema");
        Comprobante comprobante = (Comprobante) cfd.getComprobante().getComprobante();
        comprobante.getComplemento().forEach(compl -> {
            compl.getAny().forEach(comp -> {
                if (comp instanceof mx.bigdata.sat.common.nomina.v12.schema.Nomina) {
                    Nomina nomina = (Nomina) comp;
                    System.out.println(nomina.getVersion());
                }
            });
        });`

**Comment by antonioalvarezm** [comment]
Gracias por la ayuda, pero el objeto nomina es reconocido como
class com.sun.org.apache.xerces.internal.dom.ElementNSImpl

**Comment by hortegag91** [comment]
Eso pasa cuando no le mandas los contexts (no sabe a que objetos debe parsear el nodo)
Ese código que te pasé, literalmente lo corrí en mi equipo y me imprimió correctamente la versión (o cualquier atributo del nodo) sin problemas.
Te pido lo verifiques y me avises.

**Comment by antonioalvarezm** [comment]
Tienes toda la razon, me faltaba identificar el contexto.
Gracias por la ayuda.
