### ISSUE TITLE
Falla al Compilar

### ISSUE THREAD

**Issue by acordovar** [GrupoCorasa/factura-electronica#12]
He descargado el proyecto pero cuando hago Build (NetBeans) me da un error al ejecutar la clase CFDv33Test.

¿Este proyecto ya tiene el Complemento de Pago Integrado?
Si alguien seria tan amable de pasarme los binarios por favor.

Saludos!

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running mx.bigdata.sat.cfd.CFDv22Test
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.144 sec
Running mx.bigdata.sat.cfd.CFDv2Test
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.719 sec
Running mx.bigdata.sat.cfdi.CFDv32Test
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.754 sec
Running mx.bigdata.sat.cfdi.CFDv33Test
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.509 sec <<< FAILURE!
Running mx.bigdata.sat.cfdi.CFDv3Test
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.539 sec
Running mx.bigdata.sat.cfdi.TFDv1c32Test
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.41 sec
Running mx.bigdata.sat.cfdi.TFDv1Test
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.187 sec

Results :

Failed tests:   testSign(mx.bigdata.sat.cfdi.CFDv33Test): expected:<[O7geP4zL9Bm3WvwbIsvuhYza+zbm6Sp6eAM3umZfGgYGqQWW8O6YwKZXlxgsGF6jUZ3zQhBJB0oQD5XoycMKToyjJl9Dz4Ao/bQGyuJUHcQ65A+VK1+gNrP5CAda7kz2VGIVhIA35GuBFn/rxiygMVdYluG554B/Fr1NZp/70GG5VDme7eFerHwljrl6KfpUHlF+ZkSAZRWIXvtu3F63FakZTBhfR3odTM2I2g8rk6V3W+Qew8vi/qPkV54gOc2rvkf0U/aIQPHoByBma8WxQNdUi/1Odu1P3aLO1O18JFWYz+ZKxbnuvbOKM3gLiqiadsL+i8wMFk4Jf2YcGV6WqA]==> but was:<[D0hxzJKd1MPSarEcC9ngQ8WPYainIVhRkNtJL0en5TeNiQlJ8pZ0Q5g9SKiG6SIYJ7pfMQ1m6vJ6TuY28EMmk25ReYX1BN4CgtoasnZVJ5kW9TI6CMu3JKYbc2U1kWZDpSeq07lguvd2Iu0Po/uByulzVoBOPPDLHYOTX6H2VT+ER2IOAVcM8KSohO2HAEhmKx/J9dKsuu59Yn0L0X37WiySPsDyotjSR5SA8JxfeZfJxs5uqtCLlFJDNnnHuAftsui1Jq/wZXIGxmM2AP1xzbEVea6H948vge3TypPNZlwbcANpYAE3hlHhXLGuvbY+DqsAa80WSOOeq2CTTCGo3g]==>

Tests run: 39, Failures: 1, Errors: 0, Skipped: 0

------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 1:06.720s
Finished at: Mon Oct 29 17:44:38 CST 2018
Final Memory: 78M/2899M
------------------------------------------------------------------------
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project cfdi-base: There are test failures.

Please refer to D:\SistemJV\factura-electronica-master\target\surefire-reports for the individual test results.
-> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by hortegag91** [comment]
Hola, los binarios estan en el repo central de maven
Si aún no has podido builder el proyecto, te pido nos lo indiques para darte una mano.
PD: te dejo los binarios ya compilados: https://mega.nz/#!35JFRSwY!IwlYaAxwBW7fTPjba2gTN5nL5P6tFes31ZlXmXZjFVI

**Comment by supershadowuser** [comment]
Hola, solicito si me puede ayudar de favor, estoy intentando compilar y me arroja el mismo error que acordovar describe arriba.

**Comment by hortegag91** [comment]
Acabo de compilarlo y no tuve ningún inconveniente,
Te pido si pudieras indicarnos cual es tu versión exacta de Java, y si podrias intentar con el parámetro -X para ver todo el log completo por favor.
`[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:23 min
[INFO] Finished at: 2019-07-11T10:01:34-07:00
[INFO] Final Memory: 53M/1065M
[INFO] ------------------------------------------------------------------------`

**Comment by supershadowuser** [comment]
soy nuevo usando maven, estoy abriendo el proyecto desde netbeans 8.2, la versión de java que estoy utilizando es 1.8.0_131
de antemano muchas gracias

**Comment by supershadowuser** [comment]
Lo que sucede es que ya habia estado usando el jar para generar facturas con el complemento iedu, sin embargo el pac ya no me esta permitiendo timbrar por que en la validacion de los prefijos en el complemento le pone el prefijo ns3:instEducativas

**Comment by hortegag91** [comment]
Desde consola ve a la carpeta del proyecto, y ejecuta
> mvn clean install -X 
Pasa el output a un archivo txt y subelo porfa

**Comment by supershadowuser** [comment]
Hola, ejecute el comando que me indicó, sen el siguiente archivo esta las ultimas lineas del resultado ya que no puedo copiarlo todo
espero su respuesta muchas gracias
[error.txt](https://github.com/GrupoCorasa/factura-electronica/files/3383239/error.txt)

**Comment by hortegag91** [comment]
Podrias indicarme que versión del proyecto estas usando?
Puedo asumir que no has realizado cambios absolutamente en ninguna parte del código antes de intentarlo compilar?
Puedes asegurarte que el certificado que está en: resources/certs/CSD_Prueba_CFDI_LAN8507268IA.cer sea este que te anexo?
Quedo en espera 
![image](https://user-images.githubusercontent.com/14035835/61072964-3d143800-a3c9-11e9-988f-42b849203a05.png)

**Comment by supershadowuser** [comment]
Hola, solicito si me puede ayudar de favor, he descargado los archivos y estoy intentando compilar pero me arroja error, no se que ha pasado, hace aproximadamente un año descargue y compile sin problema, pero ahora que lo quiero hacer de nuevo me marca error, estoy usando la misma maquina, el mismo sistema operativo que en ocasiones pasadas. Espero su respuesta, de antemano muchas gracias. Saludos.

**Comment by supershadowuser** [comment]
Hola, aun no he podido compilar la librería, no se si influya en algo que los certificados de prueba esten caducados. Espero su respuesta, muchas gracias.

**Comment by supershadowuser** [comment]
Buenas tardes, ya logre compilar, al parecer si es algo relacionado con la vigencia de los certificados, para lograr compilar tuve que cambiar la fecha del sistema al 10 de junio del 2020. Espero pronto pueda corregir el problema. Muchas gracias.

**Comment by hortegag91** [comment]
Ya se actualizaron los certificados y los tests, deberían funcionar sin problema hasta 2023
