### ISSUE TITLE
Consulta Facturas Web Service SAT

### ISSUE THREAD

**Issue by olaft** [GrupoCorasa/factura-electronica#13]
Esta consulta no es relacionada al código fuente de este repositorio pero no encontré un mejor lugar para hacerla.  

Hasta la semana pasada utilice el web service de consulta de cfdi: https://consultaqr.facturaelectronica.sat.gob.mx/ConsultaCFDIService.svc?wsdl a partir se el lunes 5 de noviembre del 2018 ya no está disponible. Por lo que he podido investigar, ahora se tiene que autenticar el cliente para acceder a los web service del sat ¿Alguien tiene información al respecto?

Agradezco de antemano cualquier información
Saludos.

**Comment by hortegag91** [comment]
La verdad no sabría decirte cual es la razón del porqué ya no está vigente dicho webservice,
Lo que si, es que actualmente los proveedores (al menos los 3 que me ha tocado ver) manejan su propio servicio para validación de comprobantes, esto con el fin de poder brindar el servicio de cancelación a partir de los cambios aplicados el 1ro de Noviembre.

**Comment by ingtemix** [comment]
@olaft Amigo el servicio únicamente ocultaron el wsdl pero sigue aceptando peticiones.

Saludos!!!

**Comment by hortegag91** [comment]
Amigo, te adjunto un archivo rar donde vienen 2 clases de java para llamar este servicio, espero te sirvan y sientete libre de preguntar cualquier detalle. En caso de que esto solucione tu problema te pido cierres el issue. https://mega.nz/#!3kAxCIgZ!6CDV28RBPJqOKKodgzHLZH8kumTI6aLv1Nawa6akNk4

**Comment by hortegag91** [comment]
Proyecto migrado a una estructura más sustentable, por favor abrir issue en dicho repositorio
https://github.com/GrupoCorasa/cfdi-base
