### ISSUE TITLE
Cambiar los links de los documentos

### ISSUE THREAD

**Issue by efrain-perez** [GrupoCorasa/factura-electronica#14]
Hola, los links que vienen en el README del [Anexo 20](www.sat.gob.mx/informacion_fiscal/factura_electronica/Paginas/Anexo_20_version3.3.aspx) y [Complementos SAT](www.sat.gob.mx/informacion_fiscal/factura_electronica/Paginas/complementos_factura_cfdi.aspx) no funcionan actualmente. Navegando un poco por las páginas del SAT me dí cuenta que en lugar de **www**  usan **omawww** (Por razones que desconozco).

Podría decirse que cambiar **www** a **omawww** en los links lo arregla, pero estaría bien que alguien lo confirmara, soy nuevo con lo que se refiere a factura electrónica.

**Comment by hortegag91** [comment]
Podrias indicarnos en que parte te da problemas?

**Comment by hortegag91** [comment]
Proyecto migrado a una estructura más sustentable, por favor abrir issue en dicho repositorio
https://github.com/GrupoCorasa/cfdi-base
