### ISSUE TITLE
Actualizar XSD de Contabilidad electronica

### ISSUE THREAD

**Issue by Sergio70** [GrupoCorasa/factura-electronica#15]
Hola buen dia, note que la libreria no tiene las ultimas versiones de los xsd(tiene las versiones 1.1) para contabilidad electronica y actualmente es la version 1.3, si bien no cuenta con muchos cambios mas que en las cabeceras en los namespace este arroja error al momento de realizar la validacion de esctructura con la libreria con xml de la version 1.3.

serian estos xsd que se tendrian que actualizar:

- Catálogo de cuentas 
- Balanza de comprobación
- Pólizas del periodo 
- Auxiliar de folios de comprobantes fiscales
- Auxiliar de cuenta y subcuenta
- Sello Digital Contabilidad Electrónica

anexo el link sobre la documentacion:
http://omawww.sat.gob.mx/fichas_tematicas/buzon_tributario/Paginas/contabilidad_electronica.aspx

Saludos.

**Comment by hortegag91** [comment]
Ya quedaron los cambios tanto en la versión ligera como la normal. No he subido el repo ya que de momento no tengo manera rápida de probarla contra la validación del SAT.
Te pido si pudieras bajar y compilar el repositorio para hacer las pruebas correspondientes, o en su defecto, aqui te dejo un enlace de MEGA para descargarlo: https://mega.nz/#!35JFRSwY!IwlYaAxwBW7fTPjba2gTN5nL5P6tFes31ZlXmXZjFVI

**Comment by hortegag91** [comment]
Los cambios los hice en mi fork, pero ya hice el PR.
https://github.com/GrupoCorasa/factura-electronica/pull/16
