### ISSUE TITLE
cual es la diferencia entre la version lightweight y la original? s

### ISSUE THREAD

**Issue by luisgithub** [GrupoCorasa/factura-electronica#17]
Hola,
Este mas que un issue es una duda, cual es la diferencia entre la version lightweight y la original, se eliminan algunas librerias? si si cuales son?

**Comment by hortegag91** [comment]
La diferencia es que en la versión "normal" el SAT liberó los catálogos en un XSD, mismo que en algunos catalogos (código postal, claveprodserv por ejemplo) son demasiado pesados, y al cargarlos en memoria se la lleva a más de 1gb (sin mencionar que tarda mucho tiempo al momento de validar el cfdi)
En la versión light solamente lo define como un string permitiendote colocar cualquier valor, ya que no lo compara contra ningún catálogo, haciendo el proceso muchísimo más rápido y consumiendo muchísima menos memoria, pero con el riesgo que si tecleamos mal el valor, el PAC nos regresará el XML diciendo que esta mal generado.
Espero esto resuelva tu duda.
Saludos

**Comment by hortegag91** [comment]
![image](https://user-images.githubusercontent.com/14035835/62416296-bd0a7800-b5ec-11e9-93b9-d7e9097514df.png)
