### ISSUE TITLE
¿Dónde puedo descargar los binarios?

### ISSUE THREAD

**Issue by acordovar** [GrupoCorasa/factura-electronica#19]
¿Dónde puedo descargar los binarios? 
La versión LIGERA me parece muy buena alternativa, porque el problema que tengo recientemente con la librería que estaba usando se debe a que SAT actualizó sus catálogos.

Saludos y gracias de antemano.

Alexie

**Comment by hortegag91** [comment]
Los binarios puedes encontrarlos en el repositorio central de maven,
https://mvnrepository.com/artifact/mx.grupocorasa.cfdi
