### ISSUE TITLE
Como recupero los elementos y atributos

### ISSUE THREAD

**Issue by darkmaster2013** [GrupoCorasa/factura-electronica#2]
Buena tarde, necesito serializar los cfdi's que tengo para generar un reporte. 
Lo que no encuentro es como recuperar los elemento y/o en su caso los atributos del xml?
Me pueden orientar para hacer esto.

**Comment by luiscabanillas** [comment]
Hola, soy nuevo por aca, pero vamos a ver si esto te puede ayudar.

Si te refieres a procesar archvos .xml para generar datos para un reporte, en el home page de este repositorio puedes encontrar como generar un objeto CFDv33 (o un CFDvX):

``` java
Comprobante comp = CFDv32.newComprobante(new FileInputStream(file));
...
CFDv32 cfd = new CFDv32(comp);
```

La clase que utilizaras dependera de la version de CFDi en la que se haya generado cada XML. Es decir, si tu archivo XML tiene como version "3.2" entonces debes usar CFDv32, si es "3.3" entonces debes usar CFDv33, y asi segun sea el caso.

Los elementos del XML los podras obtener mediate los getters the objeto Comprobante. En el ejemplo anterior la variable 'comp'

``` java
Comprobante comp = CFDv32.newComprobante(new FileInputStream(file));
String version = comp.getVersion();
String folio = comp.getFolio();
ComprobanteEmisor emisor = comp.getEmisor();
String nombreEmisor = emisor.getNombre();
...
CFDv32 cfd = new CFDv32(comp);
```
Revisa esta opcion y comenta cualquier otra duda.

**Comment by Milo13** [comment]
hola que tal, donde puedo descargar el jar  cfdi-base 3.3.1
