### ISSUE TITLE
Falla al Compilar en Java 11

### ISSUE THREAD

**Issue by njmube** [GrupoCorasa/factura-electronica#20]
[log.txt](https://github.com/GrupoCorasa/factura-electronica/files/4183003/log.txt)

**Comment by hortegag91** [comment]
En teoría el error que marca es porque no puede parsear los xsd, has hecho alguna modificación?
En caso de que no hayas hecho modificación, podrías pasarme el archivo 
> E:/Java/factura-electronica-master/src/main/resources/xsd/common/nomina12/nomina12.xsd

**Comment by njmube** [comment]
Gracias.
