### ISSUE TITLE
Error en compilación

### ISSUE THREAD

**Issue by njmube** [GrupoCorasa/factura-electronica#21]
Al compilar muestra error en el constructor del ejemplo del método Main.

Error:(34, 22) java: no suitable constructor found for CFDv33(mx.bigdata.sat.cfdi.v33.schema.Comprobante,java.lang.String)
    constructor mx.bigdata.sat.cfdi.CFDv33.CFDv33(java.io.InputStream,java.lang.String...) is not applicable
      (argument mismatch; mx.bigdata.sat.cfdi.v33.schema.Comprobante cannot be converted to java.io.InputStream)
    constructor mx.bigdata.sat.cfdi.CFDv33.CFDv33(mx.bigdata.sat.cfd.schema.Comprobante,java.lang.String...) is not applicable
      (argument mismatch; mx.bigdata.sat.cfdi.v33.schema.Comprobante cannot be converted to mx.bigdata.sat.cfd.schema.Comprobante)

![2020-02-10_23-49-34](https://user-images.githubusercontent.com/7807456/74213749-3a7c0880-4c60-11ea-9db1-7bec0dbad155.png)

**Comment by hortegag91** [comment]
El error te dice que no existe un constructor en la clase CFDv33 que corresponda a un Comprobante y un string, pero viendo el código fuente, la clase en la línea 127 tiene este constructor
` public CFDv33(Comprobante comprobante, String... contexts) throws Exception {
        this.context = getContext(contexts);
        this.document = copy(comprobante);
    }`
por lo que en teoría si existe, podrías pasarme que constructores existen en la clase CFDv33 de tu código?

**Comment by njmube** [comment]
Buen día.

Adjunto el archivo.

![2020-02-11_09-31-51](https://user-images.githubusercontent.com/7807456/74251203-61165f80-4cb1-11ea-8c52-ea265568edb1.png)

**Comment by hortegag91** [comment]
Que versión de JDK estas usando?

**Comment by njmube** [comment]
La nueva versión estable 11.

![2020-02-11_09-39-57](https://user-images.githubusercontent.com/7807456/74251937-848dda00-4cb2-11ea-99d0-9e00e8b639d6.png)

**Comment by hortegag91** [comment]
El problema es que a partir de la versión 9, cambiaron muchas cosas que al compilar causa problemas, si te fijas muchas librerías tienen versiones antes y despues de jdk9, por lo que para compilarlo ocuparás jdk8, si agregas la librería desde maven o gradle deberías poder usarla sin problemas

**Comment by njmube** [comment]
Gracias, lo intentare.

Saludos.
