### ISSUE TITLE
Fallo en Test al compilar 

### ISSUE THREAD

**Issue by PipuDev** [GrupoCorasa/factura-electronica#22]
buen dia , baje el proyecto y trate de compilarlo pero me marca error en lo siguiente:

Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.739 sec <<< FAILURE!
testSign(mx.bigdata.sat.cfdi.CFDv33Test)  Time elapsed: 0.061 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:

<[O7geP4zL9Bm3WvwbIsvuhYza+zbm6Sp6eAM3umZfGgYGqQWW8O6YwKZXlxgsGF6jUZ3zQhBJB0oQD5XoycMKToyjJl9Dz4Ao/bQGyuJUHcQ65A+VK1+gNrP5CAda7kz2VGIVhIA35GuBFn/rxiygMVdYluG554B/Fr1NZp/70GG5VDme7eFerHwljrl6KfpUHlF+ZkSAZRWIXvtu3F63FakZTBhfR3odTM2I2g8rk6V3W+Qew8vi/qPkV54gOc2rvkf0U/aIQPHoByBma8WxQNdUi/1Odu1P3aLO1O18JFWYz+ZKxbnuvbOKM3gLiqiadsL+i8wMFk4Jf2YcGV6WqA]
==>but was:
<[D0hxzJKd1MPSarEcC9ngQ8WPYainIVhRkNtJL0en5TeNiQlJ8pZ0Q5g9SKiG6SIYJ7pfMQ1m6vJ6TuY28EMmk25ReYX1BN4CgtoasnZVJ5kW9TI6CMu3JKYbc2U1kWZDpSeq07lguvd2Iu0Po/uByulzVoBOPPDLHYOTX6H2VT+ER2IOAVcM8KSohO2HAEhmKx/J9dKsuu59Yn0L0X37WiySPsDyotjSR5SA8JxfeZfJxs5uqtCLlFJDNnnHuAftsui1Jq/wZXIGxmM2AP1xzbEVea6H948vge3TypPNZlwbcANpYAE3hlHhXLGuvbY+DqsAa80WSOOeq2CTTCGo3g]==>

**Comment by hortegag91** [comment]
Disculpa, no habia tenido tiempo de responder.
Que versión de JDK y cual IDE utilizas? Acabo de descargar desde cero el proyecto y me dejó compilarlo sin problemas.

`-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running mx.bigdata.sat.cfd.CFDv22Test
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.388 sec
Running mx.bigdata.sat.cfd.CFDv2Test
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.832 sec
Running mx.bigdata.sat.cfdi.CFDv32Test
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.808 sec
Running mx.bigdata.sat.cfdi.CFDv33Test
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.469 sec
Running mx.bigdata.sat.cfdi.CFDv3Test
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.704 sec
Running mx.bigdata.sat.cfdi.TFDv1c32Test
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.599 sec
Running mx.bigdata.sat.cfdi.TFDv1Test
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.269 sec

Results :

Tests run: 39, Failures: 0, Errors: 0, Skipped: 0`

**Comment by hortegag91** [comment]
Proyecto migrado a una estructura más sustentable, por favor abrir issue en dicho repositorio
https://github.com/GrupoCorasa/cfdi-base
