### ISSUE TITLE
Duda sobre la libreria?

### ISSUE THREAD

**Issue by johanstr001** [GrupoCorasa/factura-electronica#23]
Buenas tardes,
 mi duda es como firmar un documento pdf, word, etc.. con la efrima del sat 
o mas bien que es lo que se debe imprimir en el documento, nota utilizo JAspersoftReports, pero creo es mejor utilizar Itext para firmar en el footer del documento

**Comment by hortegag91** [comment]
Proyecto migrado a una estructura más sustentable, por favor abrir issue en dicho repositorio
https://github.com/GrupoCorasa/cfdi-base
