### ISSUE TITLE
ns3 al generar Complemento de Pago

### ISSUE THREAD

**Issue by acordovar** [GrupoCorasa/factura-electronica#24]
Buenos días,

Estoy utilizando la versión ligera.
Cuando genero un Comprobante de Pago, dentro del complemento me deja el prefijo ns3.
¿Cómo cambio de ns3 a pago10 que es lo que requiere el SAT?

Saludos!

-----------------------------------------------------------------------------------------------
<cfdi:Comprobante xmlns:**ns3**="http://www.sat.gob.mx/Pagos">

   <cfdi:Complemento>
        <**ns3**:Pagos Version="1.0">
            <**ns3**:Pago Monto="438.00" MonedaP="MXN" FormaDePagoP="03" FechaPago="2020-07-15T12:00:00">
                <**ns3**:DoctoRelacionado ImpSaldoInsoluto="0.00" ImpPagado="438.00" ImpSaldoAnt="438.00" NumParcialidad="1" MetodoDePagoDR="PPD" MonedaDR="MXN" Folio="3223" Serie="B" IdDocumento="8A230F86-F69F-4008-89A6-55F9948178BB"/>
            </**ns3**:Pago>
        </**ns3**:Pagos>
    </cfdi:Complemento>

</cfdi:Comprobante>

**Comment by hortegag91** [comment]
Hola @acordovar 
En teoría debemos agregar el context y namespace según el complemento que estemos utilizando.
En el caso de los comprobantes de pago, debemos agregar este context
`"mx.bigdata.sat.common.pagos.schema"`
y este namespace
`"http://www.sat.gob.mx/Pagos", "pago10"`

En mi caso particular tengo una librería que se encarga de toda la interacción del XML, y en dicha librería coloqué la lógica para que automáticamente implemente los context y namespace según el XML

Debes utilizar este método para crear el cfdi
`public CFDv3(InputStream in, String... contexts) throws Exception {`
Y una vez creado agregar el/los namespace
`cfdi.addNamespace(key, value)`

**Comment by acordovar** [comment]
Gracias Heriberto,

¿Tienes algun link donde pueda encontrar mas documentación al respecto?

Saludos!

**Comment by acordovar** [comment]
Gracias de nuevo Heriberto,

Ya quedo. Me hacia falta agregar el namespace solamente.

Saludos!

**Comment by hortegag91** [comment]
La verdad nunca me traje la wiki del proyecto original. De momento solo está la poca documentación dentro del código.
Las dudas que tengas con gusto acá nos apoyamos entre todos
