### ISSUE TITLE
Actualizacion en claves de Productos y Servicios en validador

### ISSUE THREAD

**Issue by Sergio70** [GrupoCorasa/factura-electronica#25]
El 16 de enero de 2020, llevó a cabo una actualización al catálogo de productos y servicios (c_ClaveProdServ); la cual incluyó varias modificaciones relevantes que deben considerarse para emitir las facturas electrónicas a partir de dicha fecha.

Ajustes presentados

Se adicionaron tres claves de productos* con vigencia desde el 16-01-2020:
15101514 – Gasolina regular menor a 91 octanos
15101515 – Gasolina premium mayor o igual a 91 octanos
15111512 – Gas natural
* Que deben incluir de manera obligatoria IVA trasladado y contienen marca 1 que permite aplicar el estímulo de IVA fronterizo.

Se estableció el fin de vigencia* de la clave:
15101506 – Gasolina
* El 15-01-2020; por lo que, ya no podrá utilizarse en el concepto o los conceptos del comprobante pues de lo contrario, al timbrarlo, marcará error.

Se modificaron dos claves de servicios para indicar que deben tener IVA trasladado:
80111700 – Reclutamiento de personal
80111701 – Servicios de contratación de personal
 

Esta actualización entró en vigor el 16 de enero de 2020 y modificó también el esquema .xsd del catálogo.

**Comment by hortegag91** [comment]
Proyecto migrado a una estructura más sustentable, por favor abrir issue en dicho repositorio
https://github.com/GrupoCorasa/cfdi-base
