### ISSUE TITLE
Ejemplo complemento detallista

### ISSUE THREAD

**Issue by acrkorn** [GrupoCorasa/factura-electronica#27]
Hola a todos,
Llevo ya algunos años usando esta librería y ahora en su nueva variente en este repo. Nunca había tenido necesidad de trabajar con addendas, pero ahora tengo que agregar a un CFDI la addenda detallista, ¿saben dónde puedo encontrar un ejemplo de cómo se implementaría usando esta librería? ¿se puede? En el repo no encontré algún ejemplo, por lo que recurro a ustedes para ver si lo han implementado y cómo.
Gracias de antemano.

**Comment by Sergio70** [comment]
Hola @acrkorn yo también he tenido que trabajar con addendas y esto es externo a la librería, por ejemplo si quieres validar el cfdi primero tendrás que quitar el nodo de la addenda, o en tu caso agregar la addenda esto después de procesar el cfdi con la libreria, etc...

**Comment by hortegag91** [comment]
Proyecto migrado a una estructura más sustentable, por favor abrir issue en dicho repositorio
https://github.com/GrupoCorasa/cfdi-base
