### ISSUE TITLE
Carta Porte

### ISSUE THREAD

**Issue by lezamablr** [GrupoCorasa/factura-electronica#29]
Saludos, hice cambios en la librería para permitir trabajar el nuevo complemento de Carta Porte... puedo subirlos? o ustedes ya están trabajando en ello?

**Comment by hortegag91** [comment]
Si pudieras hacer un pull request te lo agradecería

**Comment by lezamablr** [comment]
Perdón por mi ignorancia.... Como se hace?

**Comment by hortegag91** [comment]
Como hiciste el cambio? Le diste pull y despues lo modificaste? o le diste fork?
Si te fijas en las pestañas arriba del repo vas a ver una que dice "Pull Requests", puedes intentar googlear algún tutorial sobre como se hacen

**Comment by lezamablr** [comment]
Todo lo hice en Netbeans y le di commit, pero parece que solo batí mi propio proyecto, lo voy a pasar a eclipse y de ahí lo intento

**Comment by SistemasKimpack** [comment]
Algun novedad con este cambio ?, si es necesario como contribuimos ?  Saludos

**Comment by lezamablr** [comment]
Ya hice mi pull request con los cambios (solo para la versión ligera) ya hice pruebas locales con la creación y sellado del CFDi y exitosamente el timbrado con el PAC Prodigia, solo falta que los autoricen

**Comment by SistemasKimpack** [comment]
Ah bien Bro perfecto

**Comment by JCTOTTI10** [comment]
Brothers ya hay algun jar para implementar la carta porte ?

**Comment by lezamablr** [comment]
Solo baja la versión lightweight, compila y en la carpeta .m2 en tu directorio home se generan los jars (C:\Users\<Usuario>\.m2\repository\mx\grupocorasa\cfdi\cfdi-base-lightweight\3.3.3\)... lo ideal es que si usas maven incorpores en tu archivo pom la dependencia:
    ```
<dependency>
      <groupId>mx.grupocorasa.cfdi</groupId>
      <artifactId>cfdi-base-lightweight</artifactId>
      <version>3.3.3</version>
    </dependency>
```

**Comment by JCTOTTI10** [comment]
Gracias bro ya pude armar el .jar

**Comment by MariaDev12** [comment]
> > > @MariaDev12 ya bajaste las fuentes y las compilaste?
> > > > Solo baja la versión lightweight, compila y en la carpeta .m2 en tu directorio home se generan los jars (C:\Users\Usuario.m2\repository\mx\grupocorasa\cfdi\cfdi-base-lightweight\3.3.3)... lo ideal es que si usas maven incorpores en tu archivo pom la dependencia:
> > > > ```
> > > > <dependency>
> > > >       <groupId>mx.grupocorasa.cfdi</groupId>
> > > >       <artifactId>cfdi-base-lightweight</artifactId>
> > > >       <version>3.3.3</version>
> > > >     </dependency>
> > > > ```
> > > 
> > > 
> > > Seguramente te ha de faltar algún paso
> > 
> > 
> > Es que el archivo que me genera es este ---> "cfdi-base-lightweight-3.3.3.jar.lastUpdated" :(
> 
> Intenta borrar la carpeta .m2 o la rama correspondiente a grupocorasa e intenta compilar de nuevo, revisa que la compilación no te marque ningún error

Ya hice lo de borrar la carpeta .m2, y no mas no :( , si me sale un error pero no se como resolverlo, estoy usando eclipse, baje el zip y con ese abro el proyecto, al ponerle la dependecia de grupocorasa me marca errores, y cuando lo compilo me genera en la ruta que dices el archivo cfdi-base-lightweight-3.3.3.jar.lastUpdated, entonces no se si cuando le pongo la dependencia debo se hacerlo de alguna forma especial :(

**Comment by lezamablr** [comment]
> forma

Saludos.... perdón por no responder, ya solucionaste tu error?

**Comment by MariaDev12** [comment]
Hola @lezamablr no encuentro la forma correcta de generar el jar correcto :(, yo uso netbeans y ya hasta lo hice en ecplise y no mas no me sale :(

**Comment by hortegag91** [comment]
Proyecto migrado a una estructura más sustentable, por favor abrir issue en dicho repositorio
https://github.com/GrupoCorasa/cfdi-base
