### ISSUE TITLE
jar cfdi-base 3.3.1

### ISSUE THREAD

**Issue by Milo13** [GrupoCorasa/factura-electronica#3]
donde puedo descargar el jar cfdi-base 3.3.1

**Comment by hortegag91** [comment]
Si utilizas Maven o Gradle, puedes utilizar el group y artifact ID que aparecen en el readme del proyecto
<dependency>
  <groupId>mx.grupocorasa.cfdi</groupId>
  <artifactId>cfdi-base</artifactId>
  <version>3.3.1</version>
</dependency>
<dependency>
  <groupId>mx.grupocorasa.cfdi</groupId>
  <artifactId>cfdi-base-lightweight</artifactId>
  <version>3.3.1</version>
</dependency>
En caso contrario, puedes descargar el JAR directamente desde aqui:
Versión normal: https://oss.sonatype.org/content/groups/public/mx/grupocorasa/cfdi/cfdi-base/3.3.1/cfdi-base-3.3.1.jar
Versión ligera: https://oss.sonatype.org/content/groups/public/mx/grupocorasa/cfdi/cfdi-base-lightweight/3.3.1/cfdi-base-lightweight-3.3.1.jar

**Comment by Milo13** [comment]
ok, gracias por la ayuda, bajare y haré las pruebas.
