### ISSUE TITLE
Comprobante complemento de pago

### ISSUE THREAD

**Issue by mparamo31** [GrupoCorasa/factura-electronica#33]
Hola buena tarde
CFDv33 cfd = new CFDv33(comp,"mx.bigdata.sat.common.pagos.schema");

al correr esta instrucción, obtengo el siguiente error, alguien sabe como saolucionarlo?

Provider com.sun.xml.bind.v2.ContextFactory could not be instantiated: com.sun.xml.bind.v2.runtime.IllegalAnnotationsException: 3 counts of IllegalAnnotationExceptions
Two classes have the same XML type name "{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_TipoFactor". Use @XmlType.name and @XmlType.namespace to assign different names to them.
this problem is related to the following location:
at mx.bigdata.sat.cfdi.v33.schema.CTipoFactor
at protected mx.bigdata.sat.cfdi.v33.schema.CTipoFactor mx.bigdata.sat.cfdi.v33.schema.Comprobante$Conceptos$Concepto$Impuestos$Traslados$Traslado.tipoFactor
at mx.bigdata.sat.cfdi.v33.schema.Comprobante$Conceptos$Concepto$Impuestos$Traslados$Traslado
at protected java.util.List mx.bigdata.sat.cfdi.v33.schema.Comprobante$Conceptos$Concepto$Impuestos$Traslados.traslado
at mx.bigdata.sat.cfdi.v33.schema.Comprobante$Conceptos$Concepto$Impuestos$Traslados
at protected mx.bigdata.sat.cfdi.v33.schema.Comprobante$Conceptos$Concepto$Impuestos$Traslados mx.bigdata.sat.cfdi.v33.schema.Comprobante$Conceptos$Concepto$Impuestos.traslados
at mx.bigdata.sat.cfdi.v33.schema.Comprobante$Conceptos$Concepto$Impuestos
at protected mx.bigdata.sat.cfdi.v33.schema.Comprobante$Conceptos$Concepto$Impuestos mx.bigdata.sat.cfdi.v33.schema.Comprobante$Conceptos$Concepto.impuestos
at mx.bigdata.sat.cfdi.v33.schema.Comprobante$Conceptos$Concepto
at protected java.util.List mx.bigdata.sat.cfdi.v33.schema.Comprobante$Conceptos.concepto
at mx.bigdata.sat.cfdi.v33.schema.Comprobante$Conceptos
at public mx.bigdata.sat.cfdi.v33.schema.Comprobante$Conceptos mx.bigdata.sat.cfdi.v33.schema.ObjectFactory.createComprobanteConceptos()
at mx.bigdata.sat.cfdi.v33.schema.ObjectFactory

**Comment by hortegag91** [comment]
Proyecto migrado a una estructura más sustentable, por favor abrir issue en dicho repositorio
https://github.com/GrupoCorasa/cfdi-base

**Comment by mparamo31** [comment]
gracias! le agradezco mucho!
