### ISSUE TITLE
Duda sobre la libreria

### ISSUE THREAD

**Issue by ddominguez2093** [GrupoCorasa/factura-electronica#34]
Como se puede obtener el registro patronal a partir de un cfdi de nomina?

**Comment by hortegag91** [comment]
En teoría puede leer el archivo y despues consultarlo por medio de los complementos.
Te dejo un ejemplo, si no te permite reabres el issue.
```java
Comprobante c = CFDv33.newComprobante(new FileInputStream("resources/xmls/cfdi/v33/CFDv33_nomina.xml"));
c.getComplemento().stream().forEach(complemento ->
        complemento.getAny().stream().filter(n -> n instanceof Nomina)
                .map(n -> (Nomina) n)
                .findFirst()
                .ifPresent(nomina ->
                        System.out.println(nomina.getEmisor().getRegistroPatronal())
                )
);
```

**Comment by hortegag91** [comment]
Perdón, hay una nueva versión de la librería con los últimos cambios.
Por favor utilizar esa versión ya que esta ya no tendrá soporte.
https://github.com/GrupoCorasa/cfdi-base
