### ISSUE TITLE
Carta Porte

### ISSUE THREAD

**Issue by juanfra0064** [GrupoCorasa/factura-electronica#35]
Hola que tal.

Uso esta libreria y queria saber si se va hacer la implementacion de los nuevos cambios de hacienda referentes a carta porte?

Gracias!!!

**Comment by hortegag91** [comment]
Asi es, en teoría ya está preparada para generar CartaPorte2.0, y de igual manera al hacer el build se debería actualizar cualquier cambio en la definiciones publicadas por el SAT.
Si tienes problemas, abres un issue con el error en concreto.

**Comment by hortegag91** [comment]
Perdón, hay una nueva versión de la librería con los últimos cambios.
Por favor utilizar esa versión ya que esta ya no tendrá soporte.
https://github.com/GrupoCorasa/cfdi-base
