### ISSUE TITLE
Ejecutar el proyecto.

### ISSUE THREAD

**Issue by juanfra0064** [GrupoCorasa/factura-electronica#36]
Estoy tratando de correr el proyecto en netbeans y me aparece el siguiente error

unmappable character for encoding UTF-8

Como solucionar esto?

Gracias!!!

**Comment by hortegag91** [comment]
Tal vez puedas consultar esta publicación en stackoverflow.
Si no solucionó el problema reabres el issue porfavor.
https://stackoverflow.com/questions/12250368/error-unmappable-character-for-encoding-utf-8/15664621

**Comment by hortegag91** [comment]
Perdón, hay una nueva versión de la librería con los últimos cambios.
Por favor utilizar esa versión ya que esta ya no tendrá soporte.
https://github.com/GrupoCorasa/cfdi-base
