### ISSUE TITLE
CFDI Versión 4.0

### ISSUE THREAD

**Issue by supershadowuser** [GrupoCorasa/factura-electronica#37]
¡Hola!

Disculpa tengo una duda acerca de la librería, como sabe a partir de enero del 2022 entra en vigencia el CFDI 4.0 y pronto dejarán de ser válidos los CFDI 3.3. Mi duda es si en sus planes esta el actualizar la librería y de ser así cuando estima estará disponible, de antemano muchas gracias.

**Comment by hortegag91** [comment]
Ya existe una versión actualizada con bastantes cambios, asi como el soporte a la versión 4.0
https://github.com/GrupoCorasa/cfdi-base
Tambien cuenta con el compilado subido en github packages
https://github.com/GrupoCorasa/cfdi-base/packages/1120118

Cualquier duda, abres un issue en ese repo
