### ISSUE TITLE
Retenciones

### ISSUE THREAD

**Issue by PipeKhaos** [GrupoCorasa/factura-electronica#4]
Buen día, 

Me gustaría saber si librería esta preparada para el sellado de Comprobante Fiscal Digital a través de Internet que ampara retenciones e información de pagos, esto porque necesito sellar XML de retenciones e información de pagos y verificando el código no encontré una clase de retenciones.

Saludos.

**Comment by hortegag91** [comment]
La librería si maneja el complemento de pago, pero no está implementado el comprobante de retenciones
