### ISSUE TITLE
Problemas al generar CFDI con complemento de comercio exterior

### ISSUE THREAD

**Issue by 4Eagles** [GrupoCorasa/factura-electronica#6]
Que tal tengo un problema a la hora de generar el cfdi con complemento de comercio exterior, la excepción marca que el enumerado Pais esta en 2 lugares distintos y con el mismo namespace, ¿Alguna idea de cómo solucionarlo? toda ayuda es bien venida, gracias.

Warning general exception Ejavax.xml.bind.JAXBException: Provider com.sun.xml.bind.v2.ContextFactory could not be instantiated: com.sun.xml.bind.v2.runtime.IllegalAnnotationsException: 1 counts of IllegalAnnotationExceptions
Two classes have the same XML type name "{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_Pais". Use @XmlType.name and @XmlType.namespace to assign different names to them.
	this problem is related to the following location:
		at mx.bigdata.sat.cfdi.v33.schema.CPais
		at protected mx.bigdata.sat.cfdi.v33.schema.CPais mx.bigdata.sat.cfdi.v33.schema.Comprobante$Receptor.residenciaFiscal
		at mx.bigdata.sat.cfdi.v33.schema.Comprobante$Receptor
		at protected mx.bigdata.sat.cfdi.v33.schema.Comprobante$Receptor mx.bigdata.sat.cfdi.v33.schema.Comprobante.receptor
		at mx.bigdata.sat.cfdi.v33.schema.Comprobante
		at public mx.bigdata.sat.cfdi.v33.schema.Comprobante mx.bigdata.sat.cfdi.v33.schema.ObjectFactory.createComprobante()
		at mx.bigdata.sat.cfdi.v33.schema.ObjectFactory
	this problem is related to the following location:
		at mx.bigdata.sat.common.comercioexterior.v11.schema.CPais
		at protected mx.bigdata.sat.common.comercioexterior.v11.schema.CPais mx.bigdata.sat.common.comercioexterior.v11.schema.ComercioExterior$Receptor$Domicilio.pais
		at mx.bigdata.sat.common.comercioexterior.v11.schema.ComercioExterior$Receptor$Domicilio
		at public mx.bigdata.sat.common.comercioexterior.v11.schema.ComercioExterior$Receptor$Domicilio mx.bigdata.sat.common.comercioexterior.v11.schema.ObjectFactory.createComercioExteriorReceptorDomicilio()
		at mx.bigdata.sat.common.comercioexterior.v11.schema.ObjectFactory

**Comment by hortegag91** [comment]
Proyecto migrado a una estructura más sustentable, por favor abrir issue en dicho repositorio
https://github.com/GrupoCorasa/cfdi-base
