### ISSUE TITLE
Error al usuar ObjectFactory

### ISSUE THREAD

**Issue by dpacanins** [GrupoCorasa/factura-electronica#8]
Hola, 

estoy utilizando el jar cfdi-base-3.3.1, yo ya tenia un proyecto con la versión 3.2, y ahora que estoy utilizando la version 3 me manda el siguiente error:

Exception in thread "Thread-6" java.lang.NoClassDefFoundError: mx/bigdata/sat/cfdi/v33/schema/ObjectFactory

compilo sin problema mi proyecto pero ya en tiempo de ejecucion me indica el error anterior en la linea que contiene la siguiente instruccion   

ObjectFactory of = new ObjectFactory();

podrian apoyarme por favor, ya le di varias vueltas y nada de que quede

saludos

**Comment by hortegag91** [comment]
La librería la estas usando del repositorio maven o la compilas localmente?
El sistema presenta inestabilidad con algunas versiones de Java, si no estas usando la 1.8 te recomiendo hagas la prueba con esa.

**Comment by dpacanins** [comment]
Hola 

la estoy usando sin repositorio Maven y mi proyecto lo compile con Java 1.8

----- Mensaje original -----
De: "Heriberto Ortega Gonzalez" <notifications@github.com>
Para: "GrupoCorasa/factura-electronica" <factura-electronica@noreply.github.com>
CC: "dpacanins" <d.pacanins@lidcorp.mx>, "Author" <author@noreply.github.com>
Enviados: Jueves, 31 de Mayo 2018 16:45:39
Asunto: Re: [GrupoCorasa/factura-electronica] Error al usuar ObjectFactory (#8)



La librería la estas usando del repositorio maven o la compilas localmente? 
El sistema presenta inestabilidad con algunas versiones de Java, si no estas usando la 1.8 te recomiendo hagas la prueba con esa.

**Comment by hortegag91** [comment]
@luiscabanillas recuerdo que tu tuviste un problema similar la primera vez que lo compilaste, te acuerdas como lo solucionaste?

**Comment by dpacanins** [comment]
Hola @luiscabanillas compile con la versión de Java 8 como se recomendaba pero aun asi me seguia dando error, y alguien de aqui comento que ya habia podido descargar el codigo y habia realizado su jar sin problema y lo compartio, ese fue el que yo utilice y no me daba problemas. Pero no tenia integrado el detallista
