### ISSUE TITLE
Complemento de Pago

### ISSUE THREAD

**Issue by acordovar** [GrupoCorasa/factura-electronica#9]
¿Alguien podría indicarme cómo crear un Complemento de Pago?
De antemano, gracias!

**Comment by hortegag91** [comment]
Suponiendo que ya tengas conocimientos del uso de la librería, solo debes crear el objeto mx.bigdata.sat.common.pagos.schema.Pagos y sus objetos hijos en caso de necesitarlos, te recomiendo crearlos a través del Factory [mx.bigdata.sat.common.pagos.schema.ObjectFactory], una vez que tengamos el objeto creado y con la información correspondiente, solo debemos agregarsela al comprobante como complemento.
```
        Complemento complemento = factory.createComprobanteComplemento();
        complemento.getAny().add(**el_objeto_de_pagos**);
        **el_objeto_comprobante**.getComplemento().add(complemento);
```
En caso que no tengas ni idea de como usar la librería, te pido me digas para colocarte un ejemplo más detallado.

**Comment by acordovar** [comment]
Gracias por tu respuesta Heriberto,

Con la información que viene en el wiki logré hacerlo.
El problema era la versión de mi librería que me daba algunos errores, pero con la que alguien puso en un link de Google en el mismo wiki pude hacerlo.

Saludos!



________________________________
De: Heriberto Ortega Gonzalez <notifications@github.com>
Enviado: Tuesday, September 25, 2018 11:37:02 AM
Para: GrupoCorasa/factura-electronica
CC: acordovar; Author
Asunto: Re: [GrupoCorasa/factura-electronica] Complemento de Pago (#9)


Suponiendo que ya tengas conocimientos del uso de la librería, solo debes crear el objeto mx.bigdata.sat.common.pagos.schema.Pagos y sus objetos hijos en caso de necesitarlos, te recomiendo crearlos a través del Factory [mx.bigdata.sat.common.pagos.schema.ObjectFactory], una vez que tengamos el objeto creado y con la información correspondiente, solo debemos agregarsela al comprobante como complemento.

        Complemento complemento = factory.createComprobanteComplemento();
        complemento.getAny().add(**el_objeto_de_pagos**);
        **el_objeto_comprobante**.getComplemento().add(complemento);


En caso que no tengas ni idea de como usar la librería, te pido me digas para colocarte un ejemplo más detallado.
